import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
    content: [
        './app/**/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'on-primary-fixed': 'rgb(var(--color-on-primary-fixed-rgb) / <alpha-value>)',
                'on-primary': 'rgb(var(--color-on-primary-rgb) / <alpha-value>)',
                'secondary-fixed-dim': '#c5d6f0',
                'error-container': '#fe8983',
                'secondary-dim': '#44546a',
                'surface-dim': '#d1dce0',
                'on-secondary-container': '#435368',
                'on-background': '#2b3437',
                'tertiary-dim': '#005f40',
                'secondary': '#506076',
                'surface-container-highest': '#dbe4e7',
                'inverse-on-surface': '#9b9d9e',
                'primary': 'rgb(var(--color-primary-rgb) / <alpha-value>)',
                'on-secondary': '#f7f9ff',
                'background': '#f8f9fa',
                'on-secondary-fixed': '#314055',
                'error-dim': '#4e0309',
                'on-tertiary-container': '#005a3c',
                'tertiary-fixed-dim': '#58e7ab',
                'on-secondary-fixed-variant': '#4d5d73',
                'on-tertiary-fixed-variant': '#006544',
                'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant-rgb) / <alpha-value>)',
                'surface-container-low': '#f1f4f6',
                'outline': '#737c7f',
                'on-primary-container': 'rgb(var(--color-on-primary-container-rgb) / <alpha-value>)',
                'surface-variant': '#dbe4e7',
                'surface': '#f8f9fa',
                'on-tertiary': '#e6ffee',
                'primary-container': 'rgb(var(--color-primary-container-rgb) / <alpha-value>)',
                'surface-container-lowest': '#ffffff',
                'tertiary': '#006d4a',
                'inverse-primary': 'rgb(var(--color-inverse-primary-rgb) / <alpha-value>)',
                'secondary-fixed': '#d3e4fe',
                'secondary-container': '#d3e4fe',
                'primary-dim': 'rgb(var(--color-primary-dim-rgb) / <alpha-value>)',
                'error': '#9f403d',
                'inverse-surface': '#0c0f10',
                'on-error-container': '#752121',
                'on-tertiary-fixed': '#00452d',
                'surface-tint': 'rgb(var(--color-surface-tint-rgb) / <alpha-value>)',
                'surface-container': '#eaeff1',
                'primary-fixed': 'rgb(var(--color-primary-fixed-rgb) / <alpha-value>)',
                'surface-container-high': '#e2e9ec',
                'tertiary-fixed': '#69f6b8',
                'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim-rgb) / <alpha-value>)',
                'on-surface': '#2b3437',
                'tertiary-container': '#69f6b8',
                'on-error': '#fff7f6',
                'surface-bright': '#f8f9fa',
                'outline-variant': '#abb3b7',
                'on-surface-variant': '#586064',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontFamily: {
                headline: ['Manrope', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [forms, containerQueries],
};
